name: Build and Deploy pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 This is deploy key ${{ secrets.DEPLOY_KEY }}."
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Install and Build
      #  working-directory: OpenAPI
      #  run: npx @redocly/cli bundle openapi.yaml -o dist/librarycore7/openapi.yaml
      #
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: anastasijevic
          git-config-email: aleksandar.anastasijevic@gmail.com
          repository-name: anastasijevic/anastasijevic.github.io
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          commit-message: 'Test commit'
          branch: main
          folder: OpenAPI
          target-folder: 'test3'
          silent: true
          #clean: true