name: Build and Deploy pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Install and Build
      #  working-directory: OpenAPI
      #  run: npx @redocly/cli bundle openapi.yaml -o dist/librarycore7/openapi.yaml
      #
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: anastasijevic
          git-config-email: aleksandar.anastasijevic@gmail.com
          commit-message: 'Test commit'
          clean: true
          silent: true
          folder: OpenAPI
          branch: gh-pages
          target-folder: 'test3'
          repository-name: 'anastasijevic/anastasijevic.github.io'
          ssh-key: ${{ secrets.DEPLOY__KEY }}